// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	feedback "airbnb/features/feedback"

	mock "github.com/stretchr/testify/mock"
)

// FeedbackServiceInterface is an autogenerated mock type for the FeedbackServiceInterface type
type FeedbackServiceInterface struct {
	mock.Mock
}

// AddFeedback provides a mock function with given fields: token, homestayID, newFeedback
func (_m *FeedbackServiceInterface) AddFeedback(token interface{}, homestayID uint, newFeedback feedback.FeedbackCore) error {
	ret := _m.Called(token, homestayID, newFeedback)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint, feedback.FeedbackCore) error); ok {
		r0 = rf(token, homestayID, newFeedback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListFeedback provides a mock function with given fields: token, homestayID
func (_m *FeedbackServiceInterface) ListFeedback(token interface{}, homestayID uint) ([]feedback.FeedbackCore, error) {
	ret := _m.Called(token, homestayID)

	var r0 []feedback.FeedbackCore
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) ([]feedback.FeedbackCore, error)); ok {
		return rf(token, homestayID)
	}
	if rf, ok := ret.Get(0).(func(interface{}, uint) []feedback.FeedbackCore); ok {
		r0 = rf(token, homestayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedback.FeedbackCore)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, uint) error); ok {
		r1 = rf(token, homestayID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFeedbackServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeedbackServiceInterface creates a new instance of FeedbackServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeedbackServiceInterface(t mockConstructorTestingTNewFeedbackServiceInterface) *FeedbackServiceInterface {
	mock := &FeedbackServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
